// Contains definitions for non-craftable base items
// Prices updated to reflect the currently defined defaults for new users.
export const baseItems = {
    'чеснок': { name_ru: 'Чеснок', name_uk: 'Часник', name_en: 'Garlic', craftable: false, avgPrice: 1200 },
    'водонос': { name_ru: 'Водонос', name_uk: 'Водоніс', name_en: 'Water Carrier', craftable: false, avgPrice: 300 },
    'консервированная_фасоль': { name_ru: 'Консервированная фасоль', name_uk: 'Консервована квасоля', name_en: 'Canned Beans', craftable: false, avgPrice: 66 },
    'кислотная_крапива': { name_ru: 'Кислотная крапива', name_uk: 'Кислотна кропива', name_en: 'Acid Nettle', craftable: false, avgPrice: 300 },
    'прибор_шепота': { name_ru: 'Прибор Шепота', name_uk: 'Прилад Шепоту', name_en: 'Whisper Device', craftable: false, avgPrice: 38000 },
    'солевик': { name_ru: 'Солевик', name_uk: 'Солевик', name_en: 'Saltwort', craftable: false, avgPrice: 2000 },
    'сластена': { name_ru: 'Сластена', name_uk: 'Ласунка', name_en: 'Sweet Tooth', craftable: false, avgPrice: 7000 },
    'бледнолист': { name_ru: 'Бледнолист', name_uk: 'Блідолист', name_en: 'Paleleaf', craftable: false, avgPrice: 300 },
    'полутухлая_рыба': { name_ru: 'Полутухлая рыба', name_uk: 'Напівтухла риба', name_en: 'Semi-Rotten Fish', craftable: false, avgPrice: 6000 },
    'мясо_хрюши': { name_ru: 'Мясо хрюши', name_uk: 'М\'ясо хрюші', name_en: 'Grunt Meat', craftable: false, avgPrice: 5000 },
    'гипофиз_мертвеца': { name_ru: 'Гипофиз мертвеца', name_uk: 'Гіпофіз мерця', name_en: 'Corpse Pituitary Gland', craftable: false, avgPrice: 4000 },
    'помидор': { name_ru: 'Помидор', name_uk: 'Помідор', name_en: 'Tomato', craftable: false, avgPrice: 4000 },
    'мясо_шавки': { name_ru: 'Мясо шавки', name_uk: 'М\'ясо шавки', name_en: 'Mutt Meat', craftable: false, avgPrice: 6000 },
    'мясо_кабана': { name_ru: 'Мясо кабана', name_uk: 'М\'ясо кабана', name_en: 'Boar Meat', craftable: false, avgPrice: 6000 },
    'энергия': { name_ru: 'Энергия', name_uk: 'Енергія', name_en: 'Energy', craftable: false, avgPrice: 1 },
    'огромный_артефактный_фрагмент': { name_ru: 'Огромный артефактный фрагмент', name_uk: 'Величезний артефактний фрагмент', name_en: 'Huge Artifact Fragment', craftable: false, avgPrice: 1500 },
    'странный_артефакт': { name_ru: 'Странный артефакт', name_uk: 'Дивний артефакт', name_en: 'Strange Artifact', craftable: false, avgPrice: 2200 },
    'копыто_сильного_кабана': { name_ru: 'Копыто сильного кабана', name_uk: 'Копито сильного кабана', name_en: 'Strong Boar Hoof', craftable: false, avgPrice: 4700 },
    'реагент': { name_ru: 'Реагент', name_uk: 'Реагент', name_en: 'Reagent', craftable: false, avgPrice: 1000 },
    'банка_с_пшеном': { name_ru: 'Банка с пшеном', name_uk: 'Банка з пшеном', name_en: 'Can of Millet', craftable: false, avgPrice: 5200 },
    'банка_с_горохом': { name_ru: 'Банка с горохом', name_uk: 'Банка з горохом', name_en: 'Can of Peas', craftable: false, avgPrice: 1500 },
    'ткань': { name_ru: 'Ткань', name_uk: 'Тканина', name_en: 'Fabric', craftable: false, avgPrice: 2300 },
    'темный_лимб': { name_ru: 'Темный лимб', name_uk: 'Темній лімб', name_en: 'Dark Limb', craftable: false, avgPrice: 100000 },
    'гнилая_доска': { name_ru: 'Гнилая доска', name_uk: 'Гнила дошка', name_en: 'Rotten Plank', craftable: false, avgPrice: 2000 },
    'молоко': { name_ru: 'Молоко', name_uk: 'Молоко', name_en: 'Milk', craftable: false, avgPrice: 300 },
    'дрожжи': { name_ru: 'Дрожжи', name_uk: 'Дріжджі', name_en: 'Yeast', craftable: false, avgPrice: 5000 },
    'нефть': { name_ru: 'Нефть', name_uk: 'Нафта', name_en: 'Oil', craftable: false, avgPrice: 1439 },
    'очищенное_вещество': { name_ru: 'Очищенное вещество', name_uk: 'Очищена речовина', name_en: 'Purified Substance', craftable: false, avgPrice: 10000 },
};